import { motion } from "motion/react";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";

interface ScamMeterProps {
  score: number;
  level: "Low" | "Medium" | "High";
}

export function ScamMeter({ score, level }: ScamMeterProps) {
  const getColor = () => {
    if (level === "Low") return "bg-green-500";
    if (level === "Medium") return "bg-yellow-500";
    return "bg-red-500";
  };

  const getTextColor = () => {
    if (level === "Low") return "text-green-600";
    if (level === "Medium") return "text-yellow-600";
    return "text-red-600";
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-end">
        <div>
          <p className="text-sm font-medium text-muted-foreground uppercase tracking-wider">Scam-O-Meter</p>
          <h3 className={cn("text-3xl font-bold", getTextColor())}>{level} Risk</h3>
        </div>
        <div className="text-right">
          <span className="text-4xl font-black tabular-nums">{score}</span>
          <span className="text-sm text-muted-foreground ml-1">/100</span>
        </div>
      </div>
      
      <div className="relative h-4 w-full bg-secondary rounded-full overflow-hidden">
        <motion.div
          initial={{ width: 0 }}
          animate={{ width: `${score}%` }}
          transition={{ duration: 1, ease: "easeOut" }}
          className={cn("h-full transition-all", getColor())}
        />
      </div>
      
      <p className="text-xs text-muted-foreground italic">
        * This score is generated by AI analysis of social engineering patterns.
      </p>
    </div>
  );
}
